CREATE TABLE IF NOT EXISTS desafio (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100),
    idade INT,
    cpf VARCHAR(11),
    rg VARCHAR(30),
    data_nasc DATE,
    sexo VARCHAR(30),
    signo VARCHAR(30),
    mae VARCHAR(100),
    pai VARCHAR(100),
    email VARCHAR(100),
    senha VARCHAR(100),
    cep VARCHAR(10),
    endereco VARCHAR(100),
    numero INT,
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(100),
    telefone_fixo VARCHAR(30),
    celular VARCHAR(30),
    altura DECIMAL(3,2),
    peso DECIMAL(3,2),
    tipo_sanguineo VARCHAR(5),
    cor VARCHAR(30)
);